const mockProducts = [
  {
    id: 1,
    user_id: 1,
    category_id: 1,
    title: 'Fancy Bedroom Chair',
    description: 'Regal Bedroom Chair',
    images: 'https://lucas-furniture.co.uk/Photos/W653_Regal-Bedroom-Chair-5055299480113.jpg',
    location: 'Barcelona',
    price: 350,
    quantity: 1,
    material: "stainless steel",
    height: 83,
    depth: 52,
    width: 59,
    createdAt: "1996-08-14",
    updatedAt: "1996-08-14",
  },
  {
    id: 2,
    user_id: 1,
    category_id: 2,
    title: 'Nice Dining Table',
    description: 'Regal Oval Extending Dining Table',
    images: 'https://lucas-furniture.co.uk/Photos/W253_Regal-Oval-Extending-Table-5055299480786.jpg',
    location: 'Barcelona',
    price: 470,
    quantity: 1,
    material: "stainless steel",
    height: 76,
    depth: 107,
    width: 220,
    createdAt: "1996-08-14",
    updatedAt: "1996-08-14",
  },
  {
    id: 3,
    user_id: 1,
    category_id: 3,
    title: 'Awesome coffee table',
    description: 'Regal Oval Coffee Table',
    images: 'https://lucas-furniture.co.uk/Photos/W253_Regal-Oval-Coffee-Table-5055299480892.jpg',
    location: 'Barcelona',
    price: 210,
    quantity: 1,
    material: "stainless steel",
    height: 45,
    depth: 70,
    width: 110,
    createdAt: "1996-08-14",
    updatedAt: "1996-08-14",
  },
  {
    id: 4,
    user_id: 2,
    category_id: 1,
    title: 'Cool Bathroom Mirror',
    description: 'Black almost square bathroom mirror with shelf',
    images: 'https://cdn.rockettstgeorge.co.uk/media/catalog/product/b/l/black-almost-square-bathroom-mirror-with-shelf.jpg',
    location: 'London',
    price: 95,
    quantity: 1,
    material: "stainless steel",
    height: 50,
    depth: 17,
    width: 40,
    createdAt: "1996-08-14",
    updatedAt: "1996-08-14",
  },
  {
    id: 5,
    user_id: 2,
    category_id: 2,
    title: 'Cool Bathroom Mirror',
    description: 'Black almost square bathroom mirror with shelf',
    images: 'https://cdn.goodshomedesign.com/wp-content/uploads/2017/10/Amazing-Wood-Furniture-13-640x478.jpg',
    location: 'Barcelona',
    price: 95,
    quantity: 1,
    material: "stainless steel",
    height: 50,
    depth: 17,
    width: 40,
    createdAt: "1996-08-14",
    updatedAt: "1996-08-14",
  },
  {
    id: 6,
    user_id: 2,
    category_id: 3,
    title: "To Sara's cat",
    description: 'Black almost square bathroom mirror with shelf',
    images: 'https://www.dhoumm.co/cdn-k1/am/amazing-furniture-ideas-for-cats-nova_room-interior-and-decoration.jpg',
    location: 'Barcelona',
    price: 95,
    quantity: 1,
    material: "stainless steel",
    height: 50,
    depth: 17,
    width: 40,
    createdAt: "1996-08-14",
    updatedAt: "1996-08-14",
  }
];

const mockDeleteProduct = [
  {
    id: 6,
    user_id: 2,
    category_id: 3,
    title: "To Sara's cat",
    description: 'Black almost square bathroom mirror with shelf',
    images: 'https://www.dhoumm.co/cdn-k1/am/amazing-furniture-ideas-for-cats-nova_room-interior-and-decoration.jpg',
    location: 'Barcelona',
    price: 95,
    quantity: 1,
    material: "stainless steel",
    height: 50,
    depth: 17,
    width: 40,
    createdAt: "1996-08-14",
    updatedAt: "1996-08-14",
  },
];

const mockUpdateProduct = [
  {
    id: 1,
    user_id: 1,
    category_id: 1,
    title: 'Updated prodcut',
    description: 'This product has been updated',
    images: 'https://lucas-furniture.co.uk/Photos/W653_Regal-Bedroom-Chair-5055299480113.jpg',
    location: 'Barcelona',
    price: 1500,
    quantity: 5,
    material: "wood",
    height: 200,
    depth: 200,
    width: 200,
    createdAt: "1996-08-14",
    updatedAt: "1996-08-14",
  },
];

const mockProductEntry = {
  user_id: 1,
  category_id: 2,
  title: 'Product for testing',
  description: 'Regal Oval Extending Dining Table',
  images: 'https://lucas-furniture.co.uk/Photos/W253_Regal-Oval-Extending-Table-5055299480786.jpg',
  location: 'Barcelona',
  price: 470,
  quantity: 1,
  material: "stainless steel",
  height: 76,
  depth: 107,
  width: 220,
  createdAt: "1996-08-14",
  updatedAt: "1996-08-14",
};

const mockErrorEntryId = [
  {
    id: 999999,
    user_id: 1,
    category_id: 2,
    title: 'Nice Dining Table',
    description: 'Regal Oval Extending Dining Table',
    images: 'https://lucas-furniture.co.uk/Photos/W253_Regal-Oval-Extending-Table-5055299480786.jpg',
    location: 'Barcelona',
    price: 470,
    quantity: 1,
    material: "stainless steel",
    height: 76,
    depth: 107,
    width: 220,
    createdAt: "1996-08-14",
    updatedAt: "1996-08-14",
  },
];

function buildReq (mockBody) {
  const req = { body: mockBody, params: {} };
  return req;
}

function buildRes () {
  const res = {
    json: jest.fn(() => res).mockName('json'),
    status: jest.fn(() => res).mockName('status'),
    sendStatus: jest.fn(() => res).mockName('sendStatus'),
  };
  return res;
}

module.exports = {
  mockProducts,
  mockProductEntry,
  mockDeleteProduct,
  mockUpdateProduct,
  mockErrorEntryId,
  buildReq,
  buildRes,
};
